version: '3.1'
services:
  minecraft-exporter:
    build:
      context: .
    environment:
      RCON_HOST:
      RCON_PORT:
      RCON_PASSWORD:
    ports:
    - 9700:8000
    volumes:
    - ./world:/world:ro
