{
 "title": "minecraft Player stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "player",
    "query": "label_values(minecraft_blocks_mined,player)"
   }
  ]
 },
 "panels": [
  {
   "title": "Blocks mined",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minecraft_blocks_mined{player=\"$player\"}) by (block)",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "items crafted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minecraft_blocks_crafted{player=\"$player\"}) by (block)",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Blocks collected",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minecraft_blocks_picked_up{player=\"$player\"}) by (block)",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(minecraft_player_deaths{player=\"$player\"})"
    }
   ]
  },
  {
   "title": "Jumps",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "minecraft_player_jumps{player=\"$player\"}"
    }
   ]
  },
  {
   "title": "Meters travelled",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "expr": "minecraft_cm_traveled{player=\"$player\"} / 1000",
     "legendFormat": "{{  method }}"
    }
   ]
  },
  {
   "title": "Mobs killed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minecraft_entities_killed{player=\"$player\"}",
     "legendFormat": "{{ entity }}"
    }
   ]
  }
 ]
}