{
 "title": "Minecraft Server",
 "description": "for usage \r\nhttps://github.com/Joshi425/minecraft-exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Players Online",
   "type": "table-old",
   "gridPos": { "h": 17, "w": 3, "x": 0, "y": 0 },
   "targets": [
    { "expr": "player_online", "legendFormat": "{{player}}" }
   ]
  },
  {
   "title": "Ticktime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "dim_ticktime", "legendFormat": "{{dimension_name}}" },
    { "expr": "overall_ticktime", "legendFormat": "Overall" }
   ]
  },
  {
   "title": "TPS ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dim_tps", "legendFormat": "{{ dimension_name }}" },
    { "expr": "overall_tps", "legendFormat": "Overall" }
   ]
  },
  {
   "title": "Paper TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(paper_tps_1m)", "legendFormat": "1 Minute" },
    { "expr": "sum(paper_tps_5m)", "legendFormat": "5 Minute" },
    { "expr": "sum(paper_tps_15m)", "legendFormat": "15 Minute" }
   ]
  },
  {
   "title": "Entities Loaded",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 3, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "entities", "legendFormat": "{{ entity }}" }
   ]
  },
  {
   "title": "Play Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "player_playtime / 20", "legendFormat": "{{ player }}" }
   ]
  },
  {
   "title": "Dynmap Tile render Statistics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(dynmap_tile_render_statistics) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Score",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "player_score", "legendFormat": "{{ player }}" }
   ]
  },
  {
   "title": "Dynmap Chunk loading duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "dynmap_chunk_loading_duration", "legendFormat": "{{ type }}" }
   ]
  }
 ]
}